# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true
    trusted_proxies: '127.0.0.1'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto']

    assets:
        version: v6

    # Explicitly configure php_errors.log to address deprecation
    php_errors:
        log: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_secure: auto
        cookie_samesite: lax

when@test:
    framework:
        test: true
        session:
            handler_id: session.handler.native_file
            storage_factory_id: session.storage.factory.mock_file
        php_errors:
            log: true
