services:
  solidarity-nginx-service:
    container_name: solidarity-nginx-container
    image: nginx:1.27.4
    working_dir: '/var/www/project'
    ports: [ '1000:80' ]
    volumes:
      - './:/var/www/project'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'

  solidarity-php-service:
    container_name: solidarity-php-container
    build:
      context: .
      dockerfile: './docker/php/Dockerfile'
    working_dir: '/var/www/project'
    volumes:
      - './:/var/www/project'

  solidarity-mysql-service:
    container_name: solidarity-mysql-container
    image: mysql:8.0
    ports: [ '1001:3306' ]
    volumes:
      - 'mysql-data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=solidarity

  solidarity-mailcatcher-service:
    container_name: solidarity-mailcatcher-container
    image: axllent/mailpit:v1.24
    ports: [ '1002:8025' ]

volumes:
  mysql-data: { }
